
// fetch data and write to state
export const RECEIVE_DATA_FROM_DB = 'RECEIVE_DATA_FROM_DB'
// action by user
export const CHANGE_TEXT_FIELD = 'CHANGE_TEXT_FIELD'

export const CHANGE_RFID_CODE_TEXT_FIELD = 'CHANGE_RFID_CODE_TEXT_FIELD'

export const CHANGE_RFID_READER_CODE_TEXT_FIELD = 'CHANGE_RFID_READER_CODE_TEXT_FIELD'

export const SUBMIT_RFID = 'SUBMIT_RFID'

export const SELECT_ORDER_TO_VERIFY = 'SELECT_ORDER_TO_VERIFY'
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG'
export const CLEAR_ALL_RFID_STATE = 'CLEAR_ALL_RFID_STATE'

export const SELECT_ORDER_TAB = 'SELECT_ORDER_TAB'

export const SELECT_RADIO_BUTTON = 'SELECT_RADIO_BUTTON'

export const EMIT_SUBMIT_RFID_ERROR = 'EMIT_SUBMIT_RFID_ERROR'